### ISSUE TITLE
error after installation on Fedora Workstation 39 with Gnome 45.5

### ISSUE THREAD

**Issue by shmu26** [fablevi/OnTheTop#3]
`Error: Extension point conflict: there is already a status indicator for role OnTheTop@fablevi.github.io`

**Comment by fablevi** [comment]
Hey, IM useing ubuntu with GNOME 45. I will try to find out the problem.

**Comment by fablevi** [comment]
@shmu26 do you use some other extensions? I tested out with DING and without DING extension (there where be a bug fix with it), and its works perfectly on my machine. Can you give me more info about your system and extensions? Thanks :)

**Comment by shmu26** [comment]
Here's system info
`[shmuel@Plonter-Desktop ~] $ inxi -F
System:
  Host: Plonter-Desktop Kernel: 6.8.4-200.fc39.x86_64 arch: x86_64 bits: 64
  Desktop: GNOME v: 45.5 Distro: Fedora Linux 39 (Workstation Edition)
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME B365M-A v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2208
    date: 07/09/2021
Battery:
  ID-1: hidpp_battery_0 charge: 46% condition: N/A
CPU:
  Info: 8-core model: Intel Core i7-9700 bits: 64 type: MCP cache: L2: 2 MiB
  Speed (MHz): avg: 800 min/max: 800/4700 cores: 1: 800 2: 800 3: 800 4: 800
    5: 800 6: 800 7: 800 8: 800
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: USB C Video Adaptor driver: N/A type: USB
  Device-3: Microdia USB Live camera driver: snd-usb-audio,uvcvideo
    type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: gnome-shell driver: dri: iris gpu: i915 resolution:
    1: 1920x1080~120Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 vendor: intel mesa v: 23.3.6 renderer: Mesa Intel UHD
    Graphics 630 (CFL GT2)
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel
  Device-2: Microdia USB Live camera driver: snd-usb-audio,uvcvideo
    type: USB
  API: ALSA v: k6.8.4-200.fc39.x86_64 status: kernel-api
  Server-1: PipeWire v: 1.0.4 status: active
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: a8:5e:45:e2:87:3c
  Device-2: Realtek RTL8153 Gigabit Ethernet Adapter driver: r8152 type: USB
  IF: enp0s20f0u3u1 state: down mac: 00:e0:4c:68:51:92
  IF-ID-1: virbr0 state: up speed: 10000 Mbps duplex: unknown
    mac: 52:54:00:95:c3:43
  IF-ID-2: vnet0 state: unknown speed: 10000 Mbps duplex: full
    mac: fe:54:00:35:7d:a5
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) driver: btusb
    type: USB
  Report: btmgmt ID: hci0 state: up address: 00:1A:7D:DA:71:13 bt-v: 4.0
Drives:
  Local Storage: total: 2.26 TiB used: 1.06 TiB (46.8%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37480G size: 447.13 GiB
  ID-2: /dev/sdb vendor: Toshiba model: HDWD120 size: 1.82 TiB
Partition:
  ID-1: / size: 194.31 GiB used: 57.59 GiB (29.6%) fs: btrfs dev: /dev/sda6
  ID-2: /boot/efi size: 96 MiB used: 45.2 MiB (47.1%) fs: vfat
    dev: /dev/sda1
  ID-3: /home size: 194.31 GiB used: 57.59 GiB (29.6%) fs: btrfs
    dev: /dev/sda6
  ID-4: /var size: 194.31 GiB used: 57.59 GiB (29.6%) fs: btrfs
    dev: /dev/sda6
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 231.8 MiB (2.8%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 31.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 16 GiB available: 15.48 GiB used: 9.88 GiB (63.8%)
  Processes: 387 Uptime: 1h 17m Shell: Bash inxi: 3.3.33
[shmuel@Plonter-Desktop ~] $ 

`

**Comment by shmu26** [comment]
You know what, I reinstalled your extension, and the error is gone. :)
